### ISSUE TITLE
about ascii

### ISSUE THREAD

**Issue by youngjeff** [mevdschee/2048.c#18]
I can't understand the ascii about left arrow, right arrow, up arrow and down arrow .
I just know  letter D is 68,what about left arrow?

**Comment by mevdschee** [comment]
@youngjeff left arrow is in fact an extended character, mapping to "^[[D" or "27, 91, 68"

        <?php
        exec("stty -icanon");
        while (true) echo " ".ord(fgetc(STDIN)).",";

You can try the above PHP script and see it for yourself.
