### ISSUE TITLE
It works fine under FreeBSD

### ISSUE THREAD

**Issue by farooghkz** [mevdschee/2048.c#21]
The current version of 2048.c(not my fork) was compiled with `clang` and works fine under FreeBSD.
You may mention this in README.md

**Comment by mevdschee** [comment]
Thank you! I added it to the readme.

**Comment by farooghkz** [comment]
And a question: Should my changes and features which I add(highscores table, etc) work under FreeBSD as the current version does or GNU/Linux is enough?
