### ISSUE TITLE
Works on OpenBSD!

### ISSUE THREAD

**Issue by farooqkz** [mevdschee/2048.c#25]
Hi, I compiled 2048.c with both gcc and clang on an i386(the architecture) which was running OpenBSD and easily played it.
P.S.: I think it can be easily compiled and ran on most Unix-like operating systems including GNU/Linux, BSDs and Mac.

**Comment by mevdschee** [comment]
Great.. thank you for confirming this.

**Comment by farooqkz** [comment]
@mevdschee confirming what?
