### ISSUE TITLE
Error! Cannot read keyboard input!

### ISSUE THREAD

**Issue by DaniEzzeddine** [mevdschee/2048.c#36]
I got this error when I was trying to run it on a virtual machine, is it any solution for it?

        ·      ·      ·      ·

        4      ·      ·      2

        ·      ·      ·      ·

        ·      ·      ·      ·

            ←,↑,→,↓ or q
    Error! Cannot read keyboard input!
    $>

**Comment by mevdschee** [comment]
I don't think the standard input can be read. If you provide reproduction steps I might re-investigate.
