### ISSUE TITLE
Desktop file

### ISSUE THREAD

**Issue by mones** [mevdschee/2048.c#39]
Hi Maurits,

First, thanks for your game ;-) I like text games and yours is nice one. While packaging it for Debian I've added a desktop file and icon. It's recommended that desktop files  to be distributed upstream, so others don't have to do the same work again, so feel free to add them to your git (license is also MIT, as stated on copyright file). Files are available from packaging git:
https://salsa.debian.org/games-team/2048/-/tree/master/debian

best regards and happy new year!

**Comment by mevdschee** [comment]
Thank you for doing this, appreciated!

**Comment by mones** [comment]
You're welcome! ;-)
