### ISSUE TITLE
Tile color for 128 is not readable

### ISSUE THREAD

**Issue by lakuapik** [mevdschee/2048.c#41]
Look at the screenshot below.

![image](https://user-images.githubusercontent.com/20186786/116966204-e4b6d480-acd9-11eb-9205-bcdceaea4fd0.png)

The tile color for 128 is not readable or invisible. It is hard to read the text.

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. Did you try the other colors schemes per the README? Kind regards, Maurits

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/116966737-2aab7280-acb1-11eb-9d0a-8f0867d54aea.png)

This is how it renders on my machine.

**Comment by lakuapik** [comment]
it is my first time trying `bluered` scheme and i fell in love!

![image](https://user-images.githubusercontent.com/20186786/116968817-707f2f80-acdf-11eb-8aec-6d853b6bd01a.png)

never knew it was exists :smile:

**Comment by mevdschee** [comment]
It looks pretty! :-)
