### ISSUE TITLE
implicitly declaring library function 'snprintf' with type...

### ISSUE THREAD

**Issue by yourash** [mevdschee/2048.c#45]
gcc -o 2048 2048.c
2048.c:37:2: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
        snprintf(color,length,"\033[38;5;%d;48;5;%dm",*foreground,*background);
        ^
2048.c:37:2: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
1 error generated.

**Comment by tambow44** [comment]
Are you on MacOS? 

Add #`define _DARWIN_C_SOURCE` to the start and this will build. I had that exact error on my machine, adding that define statement fixed instantly.

**Comment by mevdschee** [comment]
I think we can rewrite the code in a safe way without using "snprintf". Let me try that.

**Comment by mevdschee** [comment]
I don't understand.. the error says:

    2048.c:37:2: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'

Yet there is such a reference, isn't there?

**Comment by tambow44** [comment]
It's an Apple-ism. Needs the `_DARWIN_C_SOURCE` to run.

**Comment by mevdschee** [comment]
>It's an Apple-ism. Needs the _DARWIN_C_SOURCE to run.

Can you try again? I removed the `snprintf` usage.

**Comment by mevdschee** [comment]
I'm assuming this error is fixed now that `snprintf` is no longer used.
