### ISSUE TITLE
When game ends, show if the score is higher than previous scores.

### ISSUE THREAD

**Issue by sohang3112** [mevdschee/2048.c#58]
This would require saving the highest score with date and time in a file. When the game ends, the high score should be shown, with a special message if the current score breaks previous high score.

**Comment by mevdschee** [comment]
There have been many proposals for high scores already. The file needs to be stored in some (standard) location, which is the biggest problem.

**Comment by sohang3112** [comment]
> The file needs to be stored in some (standard) location

@mevdschee IMO file should be saved in `~/.config` - it's a standard location for such information.

**Comment by sohang3112** [comment]
@mevdschee Are you ok with saving score information in `~/.config`? I would like to work on a PR for this - please let me know if you have any other suggestions / things I should keep in mind.

**Comment by sohang3112** [comment]
@mevdschee Please confirm if you're ok with scoring high score information in `~/.config` - then I'll work on a PR for this.

**Comment by sohang3112** [comment]
@mevdschee Closing this issue due to lack of response
