### ISSUE TITLE
Corrections to README_es.md

### ISSUE THREAD

**Issue by mones** [mevdschee/2048.c#62]
Hi Maurits,

Just noticed some strings in README_es have been translated not very accurately (some online translator perhaps? :smile:).
In Debian package I've applied this patch to fix it:

https://salsa.debian.org/games-team/2048/-/blob/master/debian/patches/readme_es.patch

Would be nice to apply it to yours.

Thanks in advance!

**Comment by mevdschee** [comment]
@mones Dear Ricardo, I don't speak Spanish, so I'm very grateful for your improvements. I'll apply them. Kind regards, Maurits

**Comment by mevdschee** [comment]
See https://github.com/mevdschee/2048.c/commit/c4f03846a47df967b967ca5f7d11fb4ef82196f4

**Comment by mones** [comment]
That was quick! Thanks! :+1:
