### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by comradecobweb** [mevdschee/2048.c#63]
I imagine it would require quite a bit of work, but I think being able to play on Windows is a good idea.

**Comment by mevdschee** [comment]
Which compiler are you targeting? MinGW?

**Comment by comradecobweb** [comment]
MinGW gcc. But in both cases you would have to change the compilation because `GNU Make` is not available for Windows.

**Comment by mevdschee** [comment]
>GNU Make is not available for Windows.

Are you sure? See: https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html

**Comment by comradecobweb** [comment]
Interesting, I had no idea about this, but don't you think cmake is better for cross-platform projects?

**Comment by mevdschee** [comment]
>don't you think cmake is better for cross-platform projects

I have no opinion on that :-)
